// This file is auto-generated by @hey-api/openapi-ts

import {
	type Client,
	formDataBodySerializer,
	type Options as Options2,
	type TDataShape,
	urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
	AddPetData,
	AddPetErrors,
	CreateUserData,
	CreateUserResponses,
	CreateUsersWithArrayInputData,
	CreateUsersWithArrayInputResponses,
	CreateUsersWithListInputData,
	CreateUsersWithListInputResponses,
	DeleteOrderData,
	DeleteOrderErrors,
	DeletePetData,
	DeletePetErrors,
	DeleteUserData,
	DeleteUserErrors,
	FindPetsByStatusData,
	FindPetsByStatusErrors,
	FindPetsByStatusResponses,
	FindPetsByTagsData,
	FindPetsByTagsErrors,
	FindPetsByTagsResponses,
	GetInventoryData,
	GetInventoryResponses,
	GetOrderByIdData,
	GetOrderByIdErrors,
	GetOrderByIdResponses,
	GetPetByIdData,
	GetPetByIdErrors,
	GetPetByIdResponses,
	GetUserByNameData,
	GetUserByNameErrors,
	GetUserByNameResponses,
	LoginUserData,
	LoginUserErrors,
	LoginUserResponses,
	LogoutUserData,
	LogoutUserResponses,
	PlaceOrderData,
	PlaceOrderErrors,
	PlaceOrderResponses,
	UpdatePetData,
	UpdatePetErrors,
	UpdatePetWithFormData,
	UpdatePetWithFormErrors,
	UpdateUserData,
	UpdateUserErrors,
	UploadFileData,
	UploadFileResponses,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

export class Pet {
	/**
	 * uploads an image
	 */
	public static uploadFile<ThrowOnError extends boolean = false>(
		options: Options<UploadFileData, ThrowOnError>,
	) {
		return (options.client ?? client).post<
			UploadFileResponses,
			unknown,
			ThrowOnError
		>({
			...formDataBodySerializer,
			security: [{ scheme: "bearer", type: "http" }],
			url: "/pet/{petId}/uploadImage",
			...options,
			headers: {
				"Content-Type": null,
				...options.headers,
			},
		});
	}

	/**
	 * Add a new pet to the store
	 */
	public static addPet<ThrowOnError extends boolean = false>(
		options: Options<AddPetData, ThrowOnError>,
	) {
		return (options.client ?? client).post<unknown, AddPetErrors, ThrowOnError>(
			{
				security: [{ scheme: "bearer", type: "http" }],
				url: "/pet",
				...options,
				headers: {
					"Content-Type": "application/json",
					...options.headers,
				},
			},
		);
	}

	/**
	 * Update an existing pet
	 */
	public static updatePet<ThrowOnError extends boolean = false>(
		options: Options<UpdatePetData, ThrowOnError>,
	) {
		return (options.client ?? client).put<
			unknown,
			UpdatePetErrors,
			ThrowOnError
		>({
			security: [{ scheme: "bearer", type: "http" }],
			url: "/pet",
			...options,
			headers: {
				"Content-Type": "application/json",
				...options.headers,
			},
		});
	}

	/**
	 * Finds Pets by status
	 *
	 * Multiple status values can be provided with comma separated strings
	 */
	public static findPetsByStatus<ThrowOnError extends boolean = false>(
		options: Options<FindPetsByStatusData, ThrowOnError>,
	) {
		return (options.client ?? client).get<
			FindPetsByStatusResponses,
			FindPetsByStatusErrors,
			ThrowOnError
		>({
			security: [{ scheme: "bearer", type: "http" }],
			url: "/pet/findByStatus",
			...options,
		});
	}

	/**
	 * Finds Pets by tags
	 *
	 * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
	 *
	 * @deprecated
	 */
	public static findPetsByTags<ThrowOnError extends boolean = false>(
		options: Options<FindPetsByTagsData, ThrowOnError>,
	) {
		return (options.client ?? client).get<
			FindPetsByTagsResponses,
			FindPetsByTagsErrors,
			ThrowOnError
		>({
			security: [{ scheme: "bearer", type: "http" }],
			url: "/pet/findByTags",
			...options,
		});
	}

	/**
	 * Deletes a pet
	 */
	public static deletePet<ThrowOnError extends boolean = false>(
		options: Options<DeletePetData, ThrowOnError>,
	) {
		return (options.client ?? client).delete<
			unknown,
			DeletePetErrors,
			ThrowOnError
		>({
			security: [{ scheme: "bearer", type: "http" }],
			url: "/pet/{petId}",
			...options,
		});
	}

	/**
	 * Find pet by ID
	 *
	 * Returns a single pet
	 */
	public static getPetById<ThrowOnError extends boolean = false>(
		options: Options<GetPetByIdData, ThrowOnError>,
	) {
		return (options.client ?? client).get<
			GetPetByIdResponses,
			GetPetByIdErrors,
			ThrowOnError
		>({
			security: [{ name: "api_key", type: "apiKey" }],
			url: "/pet/{petId}",
			...options,
		});
	}

	/**
	 * Updates a pet in the store with form data
	 */
	public static updatePetWithForm<ThrowOnError extends boolean = false>(
		options: Options<UpdatePetWithFormData, ThrowOnError>,
	) {
		return (options.client ?? client).post<
			unknown,
			UpdatePetWithFormErrors,
			ThrowOnError
		>({
			...urlSearchParamsBodySerializer,
			security: [{ scheme: "bearer", type: "http" }],
			url: "/pet/{petId}",
			...options,
			headers: {
				"Content-Type": "application/x-www-form-urlencoded",
				...options.headers,
			},
		});
	}
}

export class Store {
	/**
	 * Returns pet inventories by status
	 *
	 * Returns a map of status codes to quantities
	 */
	public static getInventory<ThrowOnError extends boolean = false>(
		options?: Options<GetInventoryData, ThrowOnError>,
	) {
		return (options?.client ?? client).get<
			GetInventoryResponses,
			unknown,
			ThrowOnError
		>({
			security: [{ name: "api_key", type: "apiKey" }],
			url: "/store/inventory",
			...options,
		});
	}

	/**
	 * Place an order for a pet
	 */
	public static placeOrder<ThrowOnError extends boolean = false>(
		options: Options<PlaceOrderData, ThrowOnError>,
	) {
		return (options.client ?? client).post<
			PlaceOrderResponses,
			PlaceOrderErrors,
			ThrowOnError
		>({
			url: "/store/order",
			...options,
			headers: {
				"Content-Type": "application/json",
				...options.headers,
			},
		});
	}

	/**
	 * Delete purchase order by ID
	 *
	 * For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
	 */
	public static deleteOrder<ThrowOnError extends boolean = false>(
		options: Options<DeleteOrderData, ThrowOnError>,
	) {
		return (options.client ?? client).delete<
			unknown,
			DeleteOrderErrors,
			ThrowOnError
		>({ url: "/store/order/{orderId}", ...options });
	}

	/**
	 * Find purchase order by ID
	 *
	 * For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
	 */
	public static getOrderById<ThrowOnError extends boolean = false>(
		options: Options<GetOrderByIdData, ThrowOnError>,
	) {
		return (options.client ?? client).get<
			GetOrderByIdResponses,
			GetOrderByIdErrors,
			ThrowOnError
		>({ url: "/store/order/{orderId}", ...options });
	}
}

export class User {
	/**
	 * Creates list of users with given input array
	 */
	public static createUsersWithListInput<ThrowOnError extends boolean = false>(
		options: Options<CreateUsersWithListInputData, ThrowOnError>,
	) {
		return (options.client ?? client).post<
			CreateUsersWithListInputResponses,
			unknown,
			ThrowOnError
		>({
			url: "/user/createWithList",
			...options,
			headers: {
				"Content-Type": "application/json",
				...options.headers,
			},
		});
	}

	/**
	 * Delete user
	 *
	 * This can only be done by the logged in user.
	 */
	public static deleteUser<ThrowOnError extends boolean = false>(
		options: Options<DeleteUserData, ThrowOnError>,
	) {
		return (options.client ?? client).delete<
			unknown,
			DeleteUserErrors,
			ThrowOnError
		>({ url: "/user/{username}", ...options });
	}

	/**
	 * Get user by user name
	 */
	public static getUserByName<ThrowOnError extends boolean = false>(
		options: Options<GetUserByNameData, ThrowOnError>,
	) {
		return (options.client ?? client).get<
			GetUserByNameResponses,
			GetUserByNameErrors,
			ThrowOnError
		>({ url: "/user/{username}", ...options });
	}

	/**
	 * Updated user
	 *
	 * This can only be done by the logged in user.
	 */
	public static updateUser<ThrowOnError extends boolean = false>(
		options: Options<UpdateUserData, ThrowOnError>,
	) {
		return (options.client ?? client).put<
			unknown,
			UpdateUserErrors,
			ThrowOnError
		>({
			url: "/user/{username}",
			...options,
			headers: {
				"Content-Type": "application/json",
				...options.headers,
			},
		});
	}

	/**
	 * Logs user into the system
	 */
	public static loginUser<ThrowOnError extends boolean = false>(
		options: Options<LoginUserData, ThrowOnError>,
	) {
		return (options.client ?? client).get<
			LoginUserResponses,
			LoginUserErrors,
			ThrowOnError
		>({ url: "/user/login", ...options });
	}

	/**
	 * Logs out current logged in user session
	 */
	public static logoutUser<ThrowOnError extends boolean = false>(
		options?: Options<LogoutUserData, ThrowOnError>,
	) {
		return (options?.client ?? client).get<
			LogoutUserResponses,
			unknown,
			ThrowOnError
		>({ url: "/user/logout", ...options });
	}

	/**
	 * Creates list of users with given input array
	 */
	public static createUsersWithArrayInput<ThrowOnError extends boolean = false>(
		options: Options<CreateUsersWithArrayInputData, ThrowOnError>,
	) {
		return (options.client ?? client).post<
			CreateUsersWithArrayInputResponses,
			unknown,
			ThrowOnError
		>({
			url: "/user/createWithArray",
			...options,
			headers: {
				"Content-Type": "application/json",
				...options.headers,
			},
		});
	}

	/**
	 * Create user
	 *
	 * This can only be done by the logged in user.
	 */
	public static createUser<ThrowOnError extends boolean = false>(
		options: Options<CreateUserData, ThrowOnError>,
	) {
		return (options.client ?? client).post<
			CreateUserResponses,
			unknown,
			ThrowOnError
		>({
			url: "/user",
			...options,
			headers: {
				"Content-Type": "application/json",
				...options.headers,
			},
		});
	}
}
